
const VERSION="1.1.0";
function corsHeaders(origin){const a=["https://fearsky2020.github.io","http://localhost:8000","http://127.0.0.1:8000"];const v=a.includes(origin)?origin:"https://fearsky2020.github.io";return{"Access-Control-Allow-Origin":v,"Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type","Access-Control-Max-Age":"86400","Vary":"Origin"}}
function json(d,s=200,o=""){return new Response(JSON.stringify(d,null,2),{status:s,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...corsHeaders(o)}})}
function cleanTitle(t){return String(t||"").replace(/\s*[|\-–—]\s*(official\s*(music\s*)?video|official\s*audio|lyrics?|mv)\s*$/i,"").replace(/\[[^\]]*(official|lyrics?|mv)[^\]]*\]/ig,"").trim()}
function iq(title,type){const t=cleanTitle(title);if(type==="staff")return[`"${t}" 五线谱 乐谱`,`"${t}" sheet music score`];if(type==="numbered")return[`"${t}" 简谱`,`"${t}" 数字谱 歌谱`];return[`"${t}" 和弦谱`,`"${t}" chord chart`]}
function wq(title,type){const t=cleanTitle(title);if(type==="staff")return[`"${t}" 五线谱 filetype:pdf`];if(type==="numbered")return[`"${t}" 简谱`];return[`"${t}" 和弦谱`]}
function host(url=""){try{return new URL(url).hostname.replace(/^www\./,"")}catch{return"网页"}}
async function imageSearch(env,q,count=10){if(!env.BRAVE_API_KEY)throw new Error("BRAVE_API_KEY is not configured");const u=new URL("https://api.search.brave.com/res/v1/images/search");u.searchParams.set("q",q);u.searchParams.set("count",String(count));u.searchParams.set("country","ALL");u.searchParams.set("safesearch","strict");const r=await fetch(u,{headers:{"Accept":"application/json","Accept-Encoding":"gzip","X-Subscription-Token":env.BRAVE_API_KEY}});if(!r.ok)throw new Error(`Brave Image Search ${r.status}: ${(await r.text()).slice(0,180)}`);return r.json()}
async function webSearch(env,q,count=6){const u=new URL("https://api.search.brave.com/res/v1/web/search");u.searchParams.set("q",q);u.searchParams.set("count",String(count));const r=await fetch(u,{headers:{"Accept":"application/json","X-Subscription-Token":env.BRAVE_API_KEY}});if(!r.ok)throw new Error(`Brave Web Search ${r.status}: ${(await r.text()).slice(0,180)}`);return r.json()}
function ni(x,type){const page=x.url||x.source||"",image=x.properties?.url||"",thumb=x.thumbnail?.src||x.thumbnail||x.properties?.placeholder||"";return{scoreType:type,source:host(page),title:x.title||"",sourcePageUrl:page,url:page,imageUrl:image,thumbnailUrl:thumb,key:"",previewType:"image",text:"",description:x.description||"",kind:"image-search"}}
function nw(x,type){const url=x.url||"";return{scoreType:type,source:host(url),title:x.title||"",sourcePageUrl:url,url,imageUrl:"",thumbnailUrl:"",key:"",previewType:/\.pdf(?:$|\?)/i.test(url)?"pdf":"page",text:"",description:x.description||"",kind:"web-fallback"}}
function dedupe(xs,es=[],eu=[]){const s=new Set(es.map(x=>String(x).toLowerCase())),u=new Set(eu),seen=new Set();return xs.filter(x=>{const id=x.imageUrl||x.thumbnailUrl||x.sourcePageUrl;if(!id||seen.has(id)||u.has(x.sourcePageUrl)||s.has(String(x.source).toLowerCase()))return false;seen.add(id);return true})}
async function searchType(env,title,type,es,eu){let imgs=[];for(const q of iq(title,type)){const d=await imageSearch(env,q,10);for(const x of(d.results||[]))imgs.push(ni(x,type))}imgs=dedupe(imgs,es,eu).filter(x=>x.thumbnailUrl||x.imageUrl).slice(0,6);if(imgs.length>=4)return imgs;let fb=[];for(const q of wq(title,type)){const d=await webSearch(env,q,6);for(const x of(d.web?.results||[]))fb.push(nw(x,type))}return dedupe([...imgs,...fb],es,eu).slice(0,8)}
export default{async fetch(request,env){const o=request.headers.get("Origin")||"";if(request.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders(o)});const url=new URL(request.url);if(request.method==="GET"&&url.pathname==="/health")return json({ok:true,service:"Worship Search Worker",version:VERSION,searchProvider:"Brave Image Search + Web Search",braveConfigured:Boolean(env.BRAVE_API_KEY)},200,o);if(request.method==="POST"&&url.pathname==="/search"){try{const b=await request.json(),title=String(b.title||"").trim();if(!title)return json({error:"title is required"},400,o);const ts=Array.isArray(b.requestedTypes)&&b.requestedTypes.length?b.requestedTypes.filter(x=>["chord","staff","numbered"].includes(x)):["chord","staff","numbered"],es=Array.isArray(b.excludeSources)?b.excludeSources:[],eu=Array.isArray(b.excludeUrls)?b.excludeUrls:[],results={chord:[],staff:[],numbered:[]};for(const type of ts)results[type]=await searchType(env,title,type,es,eu);return json({schemaVersion:"1.2",title,results,provider:"Brave Image Search + Web Search",note:"Visual previews prioritized; source links retained; no access restrictions bypassed."},200,o)}catch(e){return json({error:e.message||"search failed"},500,o)}}if(request.method==="POST"&&url.pathname==="/analyze-audio")return json({error:"NOT_IMPLEMENTED",message:"Audio analysis is not implemented in Worker V1.1."},501,o);return json({error:"Not found"},404,o)}};
