
const VERSION="1.2.0";
const VIDEO_HOSTS=["youtube.com","youtu.be","bilibili.com","v.qq.com","youku.com","douyin.com","tiktok.com","ixigua.com"];
const VIDEO_WORDS=["official video","music video"," mv "," live ","concert","karaoke","伴奏","现场","演唱会","视频"];
const POSITIVE={chord:["和弦谱","chord chart","chords","吉他谱","弹唱谱"],staff:["五线谱","sheet music","music score","piano score","乐谱","钢琴谱"],numbered:["简谱","数字谱","歌谱","numbered notation","jianpu"]};
function corsHeaders(origin){const a=["https://fearsky2020.github.io","http://localhost:8000","http://127.0.0.1:8000"];const v=a.includes(origin)?origin:"https://fearsky2020.github.io";return{"Access-Control-Allow-Origin":v,"Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type","Access-Control-Max-Age":"86400","Vary":"Origin"}}
function json(d,s=200,o=""){return new Response(JSON.stringify(d,null,2),{status:s,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...corsHeaders(o)}})}
function cleanTitle(t){return String(t||"").replace(/\s*[|\-–—]\s*(official\s*(music\s*)?video|official\s*audio|lyrics?|mv)\s*$/i,"").replace(/\[[^\]]*(official|lyrics?|mv)[^\]]*\]/ig,"").trim()}
function imageQuery(title,type){const t=cleanTitle(title);if(type==="staff")return `"${t}" 五线谱 sheet music 乐谱`;if(type==="numbered")return `"${t}" 简谱 歌谱 数字谱`;return `"${t}" 和弦谱 chord chart chords`}
function host(url=""){try{return new URL(url).hostname.replace(/^www\./,"").toLowerCase()}catch{return"网页"}}
async function imageSearch(env,q,count=30){if(!env.BRAVE_API_KEY)throw new Error("BRAVE_API_KEY is not configured");const u=new URL("https://api.search.brave.com/res/v1/images/search");u.searchParams.set("q",q);u.searchParams.set("count",String(Math.min(count,50)));u.searchParams.set("country","ALL");u.searchParams.set("safesearch","strict");const r=await fetch(u,{headers:{"Accept":"application/json","Accept-Encoding":"gzip","X-Subscription-Token":env.BRAVE_API_KEY}});if(!r.ok)throw new Error(`Brave Image Search ${r.status}: ${(await r.text()).slice(0,180)}`);return r.json()}
function normalizeImage(x,type){const page=x.url||x.source||"",image=x.properties?.url||"",thumb=x.thumbnail?.src||x.thumbnail||x.properties?.placeholder||"",width=Number(x.properties?.width||0),height=Number(x.properties?.height||0);return{scoreType:type,source:host(page),title:x.title||"",sourcePageUrl:page,url:page,imageUrl:image,thumbnailUrl:thumb,key:"",previewType:"image",text:"",description:x.description||"",kind:"image-search",width,height}}
function scoreCandidate(c,type,rejects={},preferred=[]){const text=` ${c.title||""} ${c.description||""} `.toLowerCase(),h=(c.source||"").toLowerCase();let score=0,reasons=[];if(VIDEO_HOSTS.some(x=>h===x||h.endsWith("."+x))){score-=8;reasons.push("video-host")}if(VIDEO_WORDS.some(w=>text.includes(w))){score-=5;reasons.push("video-title")}for(const w of POSITIVE[type]||[])if(text.includes(w.toLowerCase())){score+=3;reasons.push(w)}if(type==="staff"&&(h.includes("musescore")||h.includes("praisecharts")||h.includes("musicnotes"))){score+=3;reasons.push("score-site")}if(type==="numbered"&&(text.includes("简谱")||text.includes("歌谱")))score+=4;if(type==="chord"&&(text.includes("和弦谱")||text.includes("chord chart")))score+=4;if(c.width&&c.height){const ratio=c.width/c.height;if(ratio>=0.55&&ratio<=1.55){score+=2;reasons.push("document-aspect")}if(ratio>1.9){score-=2;reasons.push("wide-video-aspect")}if(c.height>=700||c.width>=900)score+=1}score-=Math.min(Number(rejects[c.source]||0)*2,6);if(preferred.includes(c.source))score+=3;return{...c,_score:score,scoreConfidence:Math.max(0,Math.min(1,(score+6)/16)),scoreReasons:reasons}}
function unique(xs,exclude=[]){const blocked=new Set(exclude),seen=new Set();return xs.filter(x=>{const id=x.imageUrl||x.thumbnailUrl||x.sourcePageUrl;if(!id||seen.has(id)||blocked.has(id)||blocked.has(x.sourcePageUrl))return false;seen.add(id);return true})}
async function searchType(env,title,type,exclude,rejects,preferred){const data=await imageSearch(env,imageQuery(title,type),30);let rows=unique((data.results||[]).map(x=>normalizeImage(x,type)),exclude).map(x=>scoreCandidate(x,type,rejects,preferred));let clean=rows.filter(x=>x._score>=1&&!x.scoreReasons.includes("video-host")&&!x.scoreReasons.includes("video-title"));if(clean.length<2)clean=rows.filter(x=>x._score>=0&&!x.scoreReasons.includes("video-host"));clean.sort((a,b)=>b._score-a._score);return clean.slice(0,3).map(({_score,...x})=>x)}
export default{async fetch(request,env){const o=request.headers.get("Origin")||"";if(request.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders(o)});const url=new URL(request.url);if(request.method==="GET"&&url.pathname==="/health")return json({ok:true,service:"Worship Search Worker",version:VERSION,searchProvider:"Brave Image Search · one request per score type",braveConfigured:Boolean(env.BRAVE_API_KEY)},200,o);if(request.method==="POST"&&url.pathname==="/search"){try{const b=await request.json(),title=String(b.title||"").trim();if(!title)return json({error:"title is required"},400,o);const ts=Array.isArray(b.requestedTypes)&&b.requestedTypes.length?b.requestedTypes.filter(x=>["chord","staff","numbered"].includes(x)):["chord","staff","numbered"],exclude=Array.isArray(b.excludeUrls)?b.excludeUrls:[],rejects=b.sourceRejectCounts&&typeof b.sourceRejectCounts==="object"?b.sourceRejectCounts:{},preferred=Array.isArray(b.preferredSources)?b.preferredSources:[],results={chord:[],staff:[],numbered:[]};for(const type of ts)results[type]=await searchType(env,title,type,exclude,rejects,preferred);return json({schemaVersion:"1.3",title,results,provider:"Brave Image Search",requestsUsed:ts.length,filter:"score-likeness-v1",note:"One image request per requested score type; video-like thumbnails filtered; top 3 returned."},200,o)}catch(e){return json({error:e.message||"search failed"},500,o)}}if(request.method==="POST"&&url.pathname==="/analyze-audio")return json({error:"NOT_IMPLEMENTED",message:"Audio analysis is not implemented in Worker V1.2."},501,o);return json({error:"Not found"},404,o)}};
